canonifyURLs: true   # prepend all relative URLs w/ baseURL
relativeURLs: false  # do NOT rewrite relative URLs to be relative to current content
uglyurls: true       # use foo.de/bar.html instead of foo.de/bar/ (our new ILIAS 7.x HTML-Lernmodul won't find landing pages else)

languageCode: "de-DE"
metaDataFormat: "yaml"
theme:
  - "hugo-lecture"
  - "hugo-theme-relearn"

themesDir: ".hugo"
contentDir: "temp/content"
publishDir: "docs"

defaultContentLanguage: "ba"
defaultContentLanguageInSubdir: true
languages:
  ba:
    baseURL: "https://www.fh-bielefeld.de/elearning/data/FH-Bielefeld/lm_data/lm_1360443/ba/"
    languageName: "Bachelor"
    title: "Bachelor"
    weight: 1
  ma:
    baseURL: "https://www.fh-bielefeld.de/elearning/data/FH-Bielefeld/lm_data/lm_1371719/ma/"
    languageName: "Master"
    title: "Master"
    weight: 2

params:
  editURL: "https://github.com/Compiler-CampusMinden/CB-Vorlesung/edit/master/markdown/"
  author: "cagix"
  themeVariant: "green"
  titleSeparator: " "
  showVisitedLinks: true
  disableBreadcrumb: true
  disableInlineCopyToClipBoard: true
  disableNextPrev: true
  disableSearch: true
  disableLandingPageButton: true
  disableLanguageSwitchingButton: true
  disableMathJax: false
  disableMermaid: true
  themeVariant:
  - "relearn-light"
  - "relearn-dark"
  - "green"

menu:
  shortcuts:
  - name: "<i class='fas fa-bookmark'></i> Fahrplan"
    url: "/index.html#fahrplan"
    weight: 10
  - name: "<i class='fas fa-bookmark'></i> Praktikum/Übung"
    url: "/assignments.html"
    weight: 10
  - name: "<i class='fas fa-bookmark'></i> Note/Credits"
    url: "/index.html#prüfungsform-note-und-credits"
    weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
    privacyEnhanced: true
